[phases.setup]
nixPkgs = ["python312", "python3Packages.pip"]

[phases.install]
cmds = [
    "pip install -r requirements.txt"
]

[start]
cmd = "gunicorn management_system.wsgi:application --bind 0.0.0.0:$PORT"
